### ISSUE TITLE
Hotkey and Menu do no initiate the JSDoc preview

### ISSUE THREAD

**Issue by the-simian** [benderTheCrime/jsdoc-preview#4]
Hello, I've spent quite some time looking through my editor to make sure I'm not overlooking anything. The issue is that when I either select the plugin from the menu, try the hotkey or even type the command in the the atom command pallette, it never engages the preview. I saw that the package seems to work similarly to the markdown preview package (which I also use). the markdown preview package works well.

I'm willing to tell you whatever you need to know about my setup to help, but I'm not sure where to begin. Here's the important parts can think of right now:

- I am using the latest version of your plugin
- I am using Atom 1.13.0
- I am using atom on windows
- I can see the hotkey is bound to the jsdoc preview in the settings
- when i hit the hotkey, it does the default editor 'duplicate line'
- I attempted to remap the key in the settings to something I was certain there was no other functionality bound to, and I still did not see the preview

I am happy to give you any more details if it will help you troubleshoot.

**Comment by benderTheCrime** [comment]
Do you see any errors in the Atom developer console?

**Comment by the-simian** [comment]
When i hit the hotkey, or use the menuitem the console does not log anything

**Comment by benderTheCrime** [comment]
Yikes, sorry about that.

Unfortunately, I don't have a whole lot of time to debug this one right now. 

Feel free to submit a pull request if you would like.

**Comment by the-simian** [comment]
Alright, I'll see if I can't figure out how to make it work. I hate submitting an issue without a PR, but I wanted to at least make sure I wasn't overlooking anything, and let you know my environment as-is. Looks like we're both equally stumped. I'll try to resolve this if I have time - thanks for reading.

**Comment by techrah** [comment]
👍

I'm using Atom 1.17.2 on macOS. I can't get the preview to launch at all either. This was in my console, though I'm not sure if it's related or not:

```
Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:41:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:306:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by benderTheCrime** [comment]
Hey, thanks for contributing to the issue. Unfortunately, I still don't have a huge amount of time for this repo. Still, feel free to submit a pull request!

**Comment by techrah** [comment]
Here's what I've uncovered so far:

In [`index.coffee`](https://github.com/benderTheCrime/jsdoc-preview/blob/03b3829421090f568328d84ad5404024365fdfeb/lib/index.coffee), there is an array of grammars. The [fourth element](https://github.com/benderTheCrime/jsdoc-preview/blob/03b3829421090f568328d84ad5404024365fdfeb/lib/index.coffee#L8) is misspelled; it should be `source.coffee`

When I try to open the pre-viewer in my own project, [`editor.getGrammar().scopeName`](https://github.com/benderTheCrime/jsdoc-preview/blob/03b3829421090f568328d84ad5404024365fdfeb/lib/index.coffee#L50) returns `source.js.jsx` which is not in the `grammars` array. If I add it to the array, then the window opens but says "No JSDocs to Preview". My project does contain some JSDoc comments.
