### ISSUE TITLE
Failed to activate the jsdoc-preview package

### ISSUE THREAD

**Issue by silverspectro** [benderTheCrime/jsdoc-preview#5]
[Enter steps to reproduce:]

1. Open Atom in a project with `atom .`
2. Watch error

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [jsdoc-preview](https://github.com/benderTheCrime/jsdoc-preview) package 1.2.1

### Stack Trace

Failed to activate the jsdoc-preview package

```
At Cannot read property 'any' of undefined

TypeError: Cannot read property 'any' of undefined
    at Object.addJSDocCustomStyles (/packages/jsdoc-preview/lib/index.coffee:87:35)
    at Object.activate (/packages/jsdoc-preview/lib/index.coffee:38:6)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-easy-jsdoc 4.10.0 
atom-minify 0.8.0 
autoclose-html 0.23.0 
autoprefixer 3.6.1 
color-picker 2.2.5 
jsdoc-preview 1.2.1 
language-babel 2.55.1 
linter 1.11.23 
linter-eslint 8.1.2 
minimap 4.26.8 
seti-syntax 1.1.2 
seti-ui 1.6.1 
status-bar-clock 2.0.4 
```

**Comment by benderTheCrime** [comment]
I'm going to need to know the version of Windows unfortunately.

Also unfortunately, as is the case with most of the issues associated with this package, I don't have a whole lot of time to debug this one right now.

Feel free to submit a pull request if you would like.
